fixed rubyver. added localhome

diff --git a/docvol b/docvol
--- a/docvol
+++ b/docvol
@@ -1,4 +1,4 @@
-#!/bin/bash
+#docker volume ls!/bin/bash
 
 # THIS RUNS FIRST
 if [ $# -eq 0 ]; then docker volume ls|grep -v -E '[a-z0-9]{64}'; exit 0; fi
@@ -16,6 +16,10 @@ function do_remove_vol {
 }
 function do_create_vol {
   local s=$(docker volume create ${VOL}) && echo "volume ${s} exists" && return 0
+}
+function do_list {
+    if ! docker volume ls|grep -v -E '[a-z0-9]{64}'|grep ${VOL}; then
+    echo "${VOL} not found"; fi
 }
 function run_inspect_container {
   if [ ${VOL} ]; then local ARY=($(docker volume inspect ${VOL}|grep -i mountpoint|sed 's/"//g; s/,//g;')); fi
@@ -67,6 +71,12 @@ case $i in
   if [ ! $# -gt 0 ]; then usage need volume arg; fi
   shift
   ;;
+-l|-list)
+  shift
+  VOL="${1}" && LVOL=1
+  shift
+  if [ ! ${VOL} ]; then usage need volume arg; fi
+  ;;
 -c|-create)
   shift
   VOL="${1}" && CVOL=1
@@ -78,6 +88,7 @@ case $i in
 esac
 done
 
+if [ ${LVOL} ]; then do_list; fi
 if [ ${INSPECT} ]; then run_inspect_container; fi
 if [ ${SIZE} ]; then get_size; fi
 if [ ${RVOL} ]; then do_remove_vol; fi
@@ -86,6 +97,7 @@ if [ ${NET} ]; then do_network; fi
 
 unset VOL
 unset RVOL
+unset LVOL
 unset CVOL
 unset INSPECT
 unset SIZE
