implemented clean for local cleanup

diff --git a/Applications/dosetup b/Applications/dosetup
--- a/Applications/dosetup
+++ b/Applications/dosetup
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 function usage {
-  echo "Usage: $*"
+  echo "Usage: $(error $*)"
   echo "./$(basename $0) -r to remove ${TESTAPP}"
   echo "./$(basename $0) -t to run: GENERATE=LOCAL ./dosetup ${TESTAPP} ${TESTPLATFORM} ${TESTVERSION}"
   echo -e "\t GENERATE=[ON | LOCAL] $(basename $0) [APP] [PLATFORM] <VERSION> <ROOT_BUILD>\n\tex: ./dosetup bestappever ubuntu 18.04"
@@ -9,6 +9,9 @@ function usage {
 }
 function msg {
   printf '\e[33m%s\e[m\n' "$*"
+}
+function error {
+  printf '\e[31m%s\e[m\n' "$*"
 }
 
 ### GLOBALS ###
@@ -305,42 +308,60 @@ function create_sandbox_runner {
   fi
 }
 
-TESTAPP="testapp"
-TESTPLATFORM="local/node"
-TESTVERSION="ubuntu"
-TESTGENERATE="GENERATE=LOCAL"
-function remove_app {
-  rm -rf ~/sandbox/assets.docker/${TESTAPP}/* rm -rf ~/sandbox/${TESTAPP} rm -rf ~/sandbox/Applications/${TESTAPP}/
-}
 function build_app {
-  echo $(GENERATE=LOCAL ./dosetup ${TESTAPP} ${TESTPLATFORM} ${TESTVERSION}) >/dev/null
+  msg "Running: GENERATE=LOCAL ./dosetup ${1} ${2} ${3}"
+  echo $(GENERATE=LOCAL ./dosetup ${1} ${2} ${3}) >/dev/null
+}
+function build_test_app {
+  local TESTAPP="testapp"
+  local TESTPLATFORM="local/node"
+  local TESTVERSION="ubuntu"
+  build_app ${TESTAPP} ${TESTPLATFORM} ${TESTVERSION}
+}
+function clean_local {
+  echo "cleaning local ${1}" && rm -rf ~/sandbox/assets.docker/${1}/* rm -rf ~/sandbox/${1} rm -rf ~/sandbox/Applications/${1}
 }
 
 ### parms
 
+TESTAPP="testapp"
 ISBUILDTEST=false
 for i in "$@"
 do
 case $i in
 -r)
-shift
-echo "removing ${TESTAPP}" && remove_app ${TESTAPP}
-exit 0
+  shift
+  clean_local ${TESTAPP}
+  exit 0
 ;;
 -t)
-shift
-ISBUILDTEST=true
-echo "removing ${TESTAPP}" && remove_app
-echo "buildling ${TESTAPP}" && build_app && msg ${TESTAPP} built
-exit 0
+  shift
+  ISBUILDTEST=true
+  clean_local ${TESTAPP}
+  build_test_app
+  msg ${TESTAPP} built
+  exit 0
+;;
+-c)
+  shift
+  toclean="${1}"
+  shift
+  if [ -z "${toclean}" ]; then usage -c expects an argument && exit ${LINENO}; fi
+    if [[ "${toclean}" == '*' ]]; then usage 'dont pass *' && exit ${LINENO}; fi
+    read -p "remove local traces of: $(msg ${toclean})? (Y/n) " yn
+    yn=${yn:-Y}
+    if [[ ! ${yn} == Y ]] && [[ ! ${yn} == y ]]; then usage clean exited && exit ${LINENO}; fi
+    echo ${toclean} removed
+  clean_local ${toclean} && msg ${toclean} cleaned
+  shift
+  exit 0
 ;;
 esac
 done
 
 ### main
 
-if [ ! ${GENERATE} ];then usage no generate;fi
-
+if [ ! ${GENERATE} ];then GENERATE="LOCAL";fi
 
 app=$1 && DEVELOPMENT_PLATFORM=$2 && PLATFORM_VERSION=$3 && ROOT_BUILD=$4
 if [ ! $app ]; then usage no app; fi
@@ -389,7 +410,6 @@ for f in setenv dobuild rundb rundev; do ln -fsn ${PWD}/${app}/$f ~/sandbox/asse
 mv ~/sandbox/assets.docker/${app}/rundev ~/sandbox/assets.docker/${app}/dev
 mv ~/sandbox/assets.docker/${app}/dobuild ~/sandbox/assets.docker/${app}/build
 
-
 create_git ${app}
 
 if [[ ${GENERATE} == LOCAL ]];
@@ -397,8 +417,10 @@ if [[ ${GENERATE} == LOCAL ]];
 elif [[ ${GENERATE} == ON ]];
   then generate_new_dockerfile ${app} ${DEVELOPMENT_PLATFORM} ${PLATFORM_VERSION} ${ROOT_BUILD};
 else
-  usage bad generate && exit ${LINENO}
+  usage bad generate
+  exit ${LINENO}
 fi
+
 
 ## BUILD DEVELOPMENT COMTAINER
 echo "Building dev container"
